use MEDIDISCEGIDREELLE
SELECT *FROM RTINFOS008
SELECT *FROM PIECEADRESSE where GPA_NUMERO='2304009' AND GPA_SOUCHE='MCC'AND GPA_TYPEPIECEADR='001'

Select * from WORDREPHASE WHERE WOP_LIGNEORDRE=1989
Select * from WORDRELIG where CAST(WOL_DATECREATION as date)= '2023-10-09' AND WOL_TYPEORDRE='VTE'
Select * from LIGNE where gl_depot = 'SI5' AND GL_NUMORDRE='2026'

Select  GPA_LIBELLE,RD8_RD8LIBDATE4,WOL_DATEACC,WOL_NUMERO,WOL_LIGNEORDRE,WOL_CODEARTICLE,WOL_LIBELLE ,WOL_QACCSAIS,WOL_LIBELLE,WOP_QACCSAIS,WOP_PHASELIB, WOP_QLANSAIS, WOP_QRECSAIS from WORDRELIG,PIECEADRESSE,RTINFOS008,WORDREPHASE
where CAST(WOL_DATECREATION as date)= '2023-10-09' AND WOL_TYPEORDRE='VTE' 
and GPA_NUMERO = WOL_NUMERO AND GPA_SOUCHE='MCC'AND GPA_TYPEPIECEADR='001'
AND RD8_CLEDATA  LIKE '%' + CAST(WOL_NUMERO AS VARCHAR(255)) + '%' and  RD8_CLEDATA LIKE '%CC%' and  RD8_CLEDATA LIKE '%000001%'
AND WOP_LIGNEORDRE = WOL_LIGNEORDRE AND WOP_PHASE NOT IN ('L11','L12','L18','L19') 


Select GPA_LIBELLE,RD8_RD8LIBDATE4,WOL_NUMERO,WOL_LIGNEORDRE,WOL_CODEARTICLE,WOL_LIBELLE ,WOL_QACCSAIS from WORDRELIG,PIECEADRESSE,RTINFOS008,WORDREPHASE
where CAST(WOL_DATECREATION as date)= '2023-10-09' AND WOL_TYPEORDRE='VTE' 
and GPA_NUMERO = WOL_NUMERO AND GPA_SOUCHE='MCC'AND GPA_TYPEPIECEADR='001'
AND RD8_CLEDATA  LIKE '%' + CAST(WOL_NUMERO AS VARCHAR(255)) + '%' and  RD8_CLEDATA LIKE '%CC%' and  RD8_CLEDATA LIKE '%000001%'
AND WOP_LIGNEORDRE = WOL_LIGNEORDRE AND WOP_PHASE NOT IN ('L11','L12','L18','L19') 

Select  GPA_LIBELLE,RD8_RD8LIBDATE4,WOL_NUMERO,WOL_LIGNEORDRE,WOL_CODEARTICLE,WOL_LIBELLE ,WOL_QACCSAIS,WOL_LIBELLE,WOP_QACCSAIS, CAST(WOP_QLANSAIS AS INT) AS WOP_QLANSAIS,
CAST(WOP_QRECSAIS AS INT) AS WOP_QRECSAIS, WOP_PHASELIB from WORDRELIG,PIECEADRESSE,RTINFOS008,WORDREPHASE
where CAST(WOL_DATECREATION as date)= '2023-10-10'  AND WOL_TYPEORDRE='VTE' 
and GPA_NUMERO = WOL_NUMERO AND GPA_SOUCHE='MCC'AND GPA_TYPEPIECEADR='001'
AND RD8_CLEDATA  LIKE '%' + CAST(WOL_NUMERO AS VARCHAR(255)) + '%' and  RD8_CLEDATA LIKE '%CC%' and  RD8_CLEDATA LIKE '%000001%'
AND WOP_LIGNEORDRE = WOL_LIGNEORDRE AND WOP_PHASE NOT IN ('L11','L12','L18','L19') 

